name: Installers for Android

on:
  workflow_dispatch: # manually triggered
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: Android
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Build installers for Android
      uses: actions/setup-node@v3
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 22.x

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - run: cd app/build; sh mustang-brand.sh
    - run: cd app; yarn install
    - run: cd lib; yarn install
    - run: cd backend; yarn install
    - run: cd mobile; yarn install
    - run: cd mobile/backend; yarn install
    - run: mkdir ~/.gyp && echo "{'variables':{'android_ndk_path':''}}" > ~/.gyp/include.gypi
    - run: cd mobile; yarn build
      env:
        NODE_OPTIONS: '--max-old-space-size=32768'
        MOBILE_ARCH: 'android-arm64'

    - run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.KEYSTORE }}' | base64 --decode > ~/private_keys/key.jks

    - run: cd mobile; npx cap sync android
    - run: cd mobile; npx cap build android --keystorepath=$HOME/private_keys/key.jks
      env:
        # KEYSTORE_PATH: $HOME/private_keys/key.jks
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_ALIAS_PASS: ${{ secrets.KEYSTORE_ALIAS_PASS }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Installers Android
        path: |
          mobile/android/app/build/outputs/bundle/release/*.apk
          mobile/android/app/build/outputs/bundle/release/*.aab
